language: java
jdk:
- oraclejdk8
script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
deploy:
  provider: heroku
  api_key:
    secure: ScMokStFmWPXLIwbp0Iyy3Avg7sugpvJtm6IvckgZ1YO+K2dMd5OLKO9GF2s3YPYMHkf2uP+O5KrMtWl5QDbNzPJtO+FFNw4vSqf7fE43inegnPjee34iQ+zLh4YMcZsII9kv9ggFdN3cqa6/S0UyddHwNgTbFmp0HRteMlGnaNkiWztlh35mUIHXvuxUlf8FYgoPTXZ9UmjUzXBU2HQqdpP6f5MlKWcscWlehwBI9pOdluDUUU4XShplMMVZdlu4OnEnxwxsn7J8f5NKDeAtDIyDNhvbkOLyZJajHScsWzQN8YK0i8whPs+aAs/r/qvQLWyhvUp2Tz2RwzXEw+DDMmQnGZHddjwpdD/rIWREvq9qIUAvOcb89yuF7bRc2owatVD+Fj1yanFe6s5Wc9UfMdG10e5SHfXZHf4gOtZnQawO9HlEPwP3NUnVDxNGBtWZ3cWfIfIN4j0VYSIwqkGWBzjwXY6opLJqOGXX6iKMxz32UZB6xHW7SYksOU1DlrPyKtoVs+7R4CHCTOItNqJ7JpMUCFOmit6jjJ6sZ99F4pbttk0gKZYi0IAwJPu8EQMIeyj5AL6D2C5EgLmmL/90KT0WoL2wajom1vmv/KsakLOZini7QwMIPeKdLtImmzBBVHaleO+2P+VAcYGMxDuVOJaLhaOyVYzJs8/vQAx9wo=
  app: jsfheroku
  on:
    repo: alerario/heroku
